//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Trailers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trailers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Trailers", typeof(Trailers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add trailer to this offer.
        /// </summary>
        public static string AddTrailerToOffer {
            get {
                return ResourceManager.GetString("AddTrailerToOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add trailer to your transport offer.
        /// </summary>
        public static string AddTrailerToYourTransportOffer {
            get {
                return ResourceManager.GetString("AddTrailerToYourTransportOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this trailer from transport offer?.
        /// </summary>
        public static string RemoveTrailerFromOffer {
            get {
                return ResourceManager.GetString("RemoveTrailerFromOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new trailer.
        /// </summary>
        public static string SaveNewTrailer {
            get {
                return ResourceManager.GetString("SaveNewTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your trailer from your saved trailers.
        /// </summary>
        public static string SelectTrailerFromSaved {
            get {
                return ResourceManager.GetString("SelectTrailerFromSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch trailer.
        /// </summary>
        public static string SwitchTrailer {
            get {
                return ResourceManager.GetString("SwitchTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use existing trailer.
        /// </summary>
        public static string UseExistingTrailer {
            get {
                return ResourceManager.GetString("UseExistingTrailer", resourceCulture);
            }
        }
    }
}
