//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Transports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Transports", typeof(Transports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new transport need.
        /// </summary>
        public static string AddNewTransportNeed {
            get {
                return ResourceManager.GetString("AddNewTransportNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new transport offer.
        /// </summary>
        public static string AddNewTransportOffer {
            get {
                return ResourceManager.GetString("AddNewTransportOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current transportData.
        /// </summary>
        public static string CurrentTransportData {
            get {
                return ResourceManager.GetString("CurrentTransportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My transport need .
        /// </summary>
        public static string MyTransportNeedToRequestAnOffer {
            get {
                return ResourceManager.GetString("MyTransportNeedToRequestAnOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My transport offer.
        /// </summary>
        public static string MyTransportOffer {
            get {
                return ResourceManager.GetString("MyTransportOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On delivery.
        /// </summary>
        public static string OnDelivery {
            get {
                return ResourceManager.GetString("OnDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending submitted transport needs.
        /// </summary>
        public static string PeningSubmittedTransportNeeds {
            get {
                return ResourceManager.GetString("PeningSubmittedTransportNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending submitted transport offers.
        /// </summary>
        public static string PeningSubmittedTransportOffers {
            get {
                return ResourceManager.GetString("PeningSubmittedTransportOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting transport offer.
        /// </summary>
        public static string RequestingTransportOffer {
            get {
                return ResourceManager.GetString("RequestingTransportOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from your saved transport needs.
        /// </summary>
        public static string SelectFromYourSavedTransportNeeds {
            get {
                return ResourceManager.GetString("SelectFromYourSavedTransportNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from your saved transport offers.
        /// </summary>
        public static string SelectFromYourSavedTransportOffers {
            get {
                return ResourceManager.GetString("SelectFromYourSavedTransportOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit transport offer.
        /// </summary>
        public static string SubmitOffer {
            get {
                return ResourceManager.GetString("SubmitOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport  need .
        /// </summary>
        public static string TransportNeed {
            get {
                return ResourceManager.GetString("TransportNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport needs waiting for Your action.
        /// </summary>
        public static string TransportNeedsWaitingForUserAction {
            get {
                return ResourceManager.GetString("TransportNeedsWaitingForUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport need to make an offer.
        /// </summary>
        public static string TransportNeedToMakeAnOffer {
            get {
                return ResourceManager.GetString("TransportNeedToMakeAnOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport offer.
        /// </summary>
        public static string TransportOffer {
            get {
                return ResourceManager.GetString("TransportOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport offers waiting for Your action.
        /// </summary>
        public static string TransportOffersWaitingForUserAction {
            get {
                return ResourceManager.GetString("TransportOffersWaitingForUserAction", resourceCulture);
            }
        }
    }
}
