//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransportOffers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransportOffers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.TransportOffers", typeof(TransportOffers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change vehicle for this offer.
        /// </summary>
        public static string ChangeTransportOfferVehicle {
            get {
                return ResourceManager.GetString("ChangeTransportOfferVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request transport.
        /// </summary>
        public static string RequestTransport {
            get {
                return ResourceManager.GetString("RequestTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save vehicle for transport offer.
        /// </summary>
        public static string SaveVehicleForTransportOffer {
            get {
                return ResourceManager.GetString("SaveVehicleForTransportOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from saved vehicles.
        /// </summary>
        public static string SelectFromSaved {
            get {
                return ResourceManager.GetString("SelectFromSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select vehicle for Your  transport offer.
        /// </summary>
        public static string SelectVehicleForYourOffer {
            get {
                return ResourceManager.GetString("SelectVehicleForYourOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch trailer.
        /// </summary>
        public static string SwitchTrailer {
            get {
                return ResourceManager.GetString("SwitchTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch vehicle.
        /// </summary>
        public static string SwitchVehicle {
            get {
                return ResourceManager.GetString("SwitchVehicle", resourceCulture);
            }
        }
    }
}
