//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources.Areas.Identity.Pages.Account.Manage {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnableAuthenticator {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnableAuthenticator() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Base.Resources.Areas.Identity.Pages.Account.Manage.EnableAuthenticator", typeof(EnableAuthenticator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ConfigureAuthenticatorApp {
            get {
                return ResourceManager.GetString("ConfigureAuthenticatorApp", resourceCulture);
            }
        }
        
        public static string ToUseAuthenticatorApp {
            get {
                return ResourceManager.GetString("ToUseAuthenticatorApp", resourceCulture);
            }
        }
        
        public static string HowToGetAuthenticatorApp {
            get {
                return ResourceManager.GetString("HowToGetAuthenticatorApp", resourceCulture);
            }
        }
        
        public static string ScanTheQRCode {
            get {
                return ResourceManager.GetString("ScanTheQRCode", resourceCulture);
            }
        }
        
        public static string IntoAuthenticatorApp {
            get {
                return ResourceManager.GetString("IntoAuthenticatorApp", resourceCulture);
            }
        }
        
        public static string LearnHowTo {
            get {
                return ResourceManager.GetString("LearnHowTo", resourceCulture);
            }
        }
        
        public static string OnceYouHaveScanned {
            get {
                return ResourceManager.GetString("OnceYouHaveScanned", resourceCulture);
            }
        }
        
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
    }
}
