//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources.Areas.Identity.Pages.Account.Manage {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TwoFactorAuthentication {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TwoFactorAuthentication() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Base.Resources.Areas.Identity.Pages.Account.Manage.TwoFactorAuthentication", typeof(TwoFactorAuthentication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string TwoFactorAuthenticationTitle {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationTitle", resourceCulture);
            }
        }
        
        public static string YouHaveNoRecoveryCodesLeft {
            get {
                return ResourceManager.GetString("YouHaveNoRecoveryCodesLeft", resourceCulture);
            }
        }
        
        public static string YouMust {
            get {
                return ResourceManager.GetString("YouMust", resourceCulture);
            }
        }
        
        public static string GenerateANewSetOfRecoveryCodes {
            get {
                return ResourceManager.GetString("GenerateANewSetOfRecoveryCodes", resourceCulture);
            }
        }
        
        public static string BeforeLoginWithRecoveryCode {
            get {
                return ResourceManager.GetString("BeforeLoginWithRecoveryCode", resourceCulture);
            }
        }
        
        public static string YouHaveOneRecoveryCodeLeft {
            get {
                return ResourceManager.GetString("YouHaveOneRecoveryCodeLeft", resourceCulture);
            }
        }
        
        public static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
        
        public static string YouHave {
            get {
                return ResourceManager.GetString("YouHave", resourceCulture);
            }
        }
        
        public static string RecoveryCodesLeft {
            get {
                return ResourceManager.GetString("RecoveryCodesLeft", resourceCulture);
            }
        }
        
        public static string YouShould {
            get {
                return ResourceManager.GetString("YouShould", resourceCulture);
            }
        }
        
        public static string ForgetThisBrowser {
            get {
                return ResourceManager.GetString("ForgetThisBrowser", resourceCulture);
            }
        }
        
        public static string Disable2FA {
            get {
                return ResourceManager.GetString("Disable2FA", resourceCulture);
            }
        }
        
        public static string ResetRecoveryCodes {
            get {
                return ResourceManager.GetString("ResetRecoveryCodes", resourceCulture);
            }
        }
        
        public static string AuthenticatorApp {
            get {
                return ResourceManager.GetString("AuthenticatorApp", resourceCulture);
            }
        }
        
        public static string AddAuthenticatorApp {
            get {
                return ResourceManager.GetString("AddAuthenticatorApp", resourceCulture);
            }
        }
        
        public static string SetupAuthenticatorApp {
            get {
                return ResourceManager.GetString("SetupAuthenticatorApp", resourceCulture);
            }
        }
        
        public static string ResetAuthenticatorApp {
            get {
                return ResourceManager.GetString("ResetAuthenticatorApp", resourceCulture);
            }
        }
    }
}
