//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.BLL.App.DTO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Organisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Organisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BLL.App.DTO.Organisation", typeof(Organisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string _Organisation {
            get {
                return ResourceManager.GetString("_Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisations.
        /// </summary>
        public static string _Organisations {
            get {
                return ResourceManager.GetString("_Organisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer count.
        /// </summary>
        public static string TrailerCount {
            get {
                return ResourceManager.GetString("TrailerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport need count.
        /// </summary>
        public static string TransportNeedCount {
            get {
                return ResourceManager.GetString("TransportNeedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport offer count.
        /// </summary>
        public static string TransportOfferCount {
            get {
                return ResourceManager.GetString("TransportOfferCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User count.
        /// </summary>
        public static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle count.
        /// </summary>
        public static string VehicleCount {
            get {
                return ResourceManager.GetString("VehicleCount", resourceCulture);
            }
        }
    }
}
