//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.BLL.App.DTO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Transport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BLL.App.DTO.Transport", typeof(Transport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        public static string _Transport {
            get {
                return ResourceManager.GetString("_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transports.
        /// </summary>
        public static string _Transports {
            get {
                return ResourceManager.GetString("_Transports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered time.
        /// </summary>
        public static string DeliveredTime {
            get {
                return ResourceManager.GetString("DeliveredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated delivery time.
        /// </summary>
        public static string EstimatedDeliveryTime {
            get {
                return ResourceManager.GetString("EstimatedDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final price.
        /// </summary>
        public static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup location.
        /// </summary>
        public static string PickUpLocation {
            get {
                return ResourceManager.GetString("PickUpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup time.
        /// </summary>
        public static string PickUpTime {
            get {
                return ResourceManager.GetString("PickUpTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TransportStatus {
            get {
                return ResourceManager.GetString("TransportStatus", resourceCulture);
            }
        }
    }
}
