//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Li Ve Ry.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User organisations.
        /// </summary>
        public static string AppUserOrganisations {
            get {
                return ResourceManager.GetString("AppUserOrganisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRUD pages.
        /// </summary>
        public static string Crud {
            get {
                return ResourceManager.GetString("Crud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here yet....
        /// </summary>
        public static string EmptyListItemNothingHere {
            get {
                return ResourceManager.GetString("EmptyListItemNothingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language strings.
        /// </summary>
        public static string LangStrings {
            get {
                return ResourceManager.GetString("LangStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No organisation.
        /// </summary>
        public static string NoOrganisation {
            get {
                return ResourceManager.GetString("NoOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trailer.
        /// </summary>
        public static string NoTrailer {
            get {
                return ResourceManager.GetString("NoTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisational.
        /// </summary>
        public static string Organisational {
            get {
                return ResourceManager.GetString("Organisational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisations.
        /// </summary>
        public static string Organisations {
            get {
                return ResourceManager.GetString("Organisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcels.
        /// </summary>
        public static string Parcels {
            get {
                return ResourceManager.GetString("Parcels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        public static string SaveContinue {
            get {
                return ResourceManager.GetString("SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers.
        /// </summary>
        public static string Trailers {
            get {
                return ResourceManager.GetString("Trailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string TransLations {
            get {
                return ResourceManager.GetString("TransLations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport metainfos.
        /// </summary>
        public static string TransportMetas {
            get {
                return ResourceManager.GetString("TransportMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport needs.
        /// </summary>
        public static string TransportNeeds {
            get {
                return ResourceManager.GetString("TransportNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport offers.
        /// </summary>
        public static string TransportOffers {
            get {
                return ResourceManager.GetString("TransportOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transports.
        /// </summary>
        public static string Transports {
            get {
                return ResourceManager.GetString("Transports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users and roles.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle types.
        /// </summary>
        public static string VehicleTypes {
            get {
                return ResourceManager.GetString("VehicleTypes", resourceCulture);
            }
        }
    }
}
